name: Update Hourly and 15-Min Predictions

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write  # Allow workflow to push commits

jobs:
  predict-intraday:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate Hourly and 15-Min Predictions
      run: |
        echo "Generating intraday predictions..."
        python utils/predict_hourly_and_15min.py
        
    - name: Commit and push predictions
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/predictions/
        git diff --quiet && git diff --staged --quiet || (git commit -m "⚡ Intraday predictions - $(date +'%Y-%m-%d %H:%M UTC')" && git push)
